# Generated by Django 3.0.2 on 2020-05-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_requestmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='ppe',
            field=models.IntegerField(default=0),
        ),
    ]
