# Generated by Django 3.0.2 on 2020-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_donor_ppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='handles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='openers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='shields',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='straps',
            field=models.IntegerField(default=0),
        ),
    ]
